baseurl = "http://a4p-website-aubort.c9users.io/"
languageCode = "en-us"
title = "A4P - All for Projects"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"



[params]
    author = "pascal aubort"
    primaryColor = "mdl-color--blue-grey-900"
    # Enter your tracking code to enable Google Analytics
    googleAnalytics = "UA-73219735-1"
    
    [params.navigation]
        categories = ['About us', 'Clients & Partners', 'References', 'Contacts']

    [params.content.about]
        title = 'About us'
        content = ""
    
    [params.content.casestudies]
        title = 'References'
        content = "asd"
        
    